version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "reladraw"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
